### ISSUE TITLE
Update a park name in the industrial parks cube

### ISSUE THREAD

**Issue by azapatam** [datamexico/data-etl#238]
![image](https://user-images.githubusercontent.com/42551166/149537257-7b609dce-5c46-420f-8f03-48833e3aa889.png)

**Comment by oportusgonzalo** [comment]
Changes already applied and visible in Tesseract UI.

<img src="https://i.ibb.co/Lk488W0/Captura-de-Pantalla-2022-01-17-a-la-s-11-59-45.png" alt="Captura-de-Pantalla-2022-01-17-a-la-s-11-59-45" border="0">
