### ISSUE TITLE
Update data

### ISSUE THREAD

**Issue by azapatam** [datamexico/data-etl#253]
Everything in yellow in [our spreadsheet](https://docs.google.com/spreadsheets/d/147QUN9GTEFnnGKIPF89GiIqV4T8KGkPmlwCMNP43oRk/edit#gid=0) has data to update. I leave the list in order of priority and do not forget to update the spreadsheet.
- [x] ENOE
- [x] Foreign Trade BCMM (the data is in CGP)
- [x] Foreign Trade Banxico
- [x] Foreing Trade INEGI
- [x] Foreign Direct Investment (the data is in your email)
- [x] INEA
- [x] Budget Transparency
- [x] ENVIPE
- [x] SESNSP
- [x] Remmitances
- [x] Infonavit (review if exist new data)

**Comment by oportusgonzalo** [comment]
Budget transparency has no new data. On the other hand, infonavit was updated recently by Miguel !
