### ISSUE TITLE
create "data inventory" spreadsheet with all datasets

### ISSUE THREAD

**Issue by alexandersimoes** [datamexico/data-etl#39]
As you guys are going through each of the datasets, it would be great to have a spreadsheet we could reference with the client of all the datasets we have ingested including the years that are available and any other specific comments.

**Comment by D2SD** [comment]
So far we have this, what other information do you think will be useful to have?
https://docs.google.com/spreadsheets/d/12MdLOKyFiIvheIgKWVRT9WbxW-n02553K3FgJ6kJeRM/edit?usp=sharing
