### ISSUE TITLE
fix broken occupation cuts for inegi_enoe cube

### ISSUE THREAD

**Issue by alexandersimoes** [datamexico/data-etl#40]
broken endpoint:
https://api.datamexico.org/tesseract/cubes/inegi_enoe/aggregate.jsonrecords?drilldowns%5B%5D=Geography.Location&measures%5B%5D=Wage&measures%5B%5D=Workforce&parents=false&sparse=false&cuts[]=Occupation+Actual+Job.Occupation.Occupation.1111

 trying to cut on a specific occupation in the `inegi_enoe` cube

**Comment by cnavarreteliz** [comment]
solved via [7f6f8c6e](https://github.com/datamexico/datamexico-tesseract/commit/7f6f8c6eff51a1a0fe7087952c0b6aa395b91b62)
